version: '3.9'

services:
  api:
    restart: always
    build:
      context: .
      args:
        - DEV=true
    environment:
      - DEV=true
      - PORT=8000
      - HOST=localhost
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=db
      - MONGO_USER=root
      - MONGO_PASSWORD=password
      - SP_ID=${SP_ID}
      - SP_SECRET=${SP_SECRET}
    ports:
      - 8000:8000
    depends_on:
      - mongo
    volumes:
      - ./src:/app/src
    command: npm run dev
  
  mongo:
    image: mongo:6.0.10
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=db
    command: mongod --quiet --logpath=/dev/null

volumes:
  data:
