version: '3.9'

services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      args:
        - DEV=true
    environment:
      - DEV=true
      - PORT=8000
      - HOST=localhost
      - DB_PORT=5432
      - DB_NAME=db_name
      - DB_USER=postgres
      - DB_PASSWORD=password
      - SP_ID=${SP_ID}
      - SP_SECRET=${SP_SECRET}
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    command: npm run dev

  db:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes:
  data:
