version: '3.9'

services:
  api:
    container_name: api
    restart: always
    build: .
    environment:
      - DEV=true
      - PORT=${PORT}
      - HOST=${HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SP_ID=${SP_ID}
      - SP_SECRET=${SP_SECRET}
    ports:
      - ${PORT}:8000
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev

  db:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  data:
