services:
  server:
    restart: always
    build:
      context: ./
      dockerfile: ./server/Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - PORT=8000
      - HOST=localhost
      - JWT_SECRET_KEY=changeme
      - TOKEN_HEADER_KEY=Authorization
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=db
      - MONGO_USER=root
      - MONGO_PASSWORD=changeme
      - MONGO_URI=mongodb://root:changeme@mongo-jbx:27017
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - LOG_LEVEL=debug
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    volumes:
      - ./server:/app/server
      - ./jest.config.ts:/app/jest.config.ts
      - ./packages:/app/packages
      # - ./dist:/app/dist
    command: npm run dev

  mongodb:
    image: mongo:6.0.9
    restart: always
    container_name: mongo-jbx
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=changeme
    command: mongod --quiet --logpath /dev/null --bind_ip_all

volumes:
  data:
